update git pre-commit hook to ensure ansible-lint python module is installed on client

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,11 +1,6 @@
 #!/bin/sh
 #
-# An example hook script to verify what is about to be committed.
-# Called by "git commit" with no arguments.  The hook should
-# exit with non-zero status after issuing an appropriate message if
-# it wants to stop the commit.
-#
-# To enable this hook, rename this file to "pre-commit".
+EXIT_CODE=0
 
 if git rev-parse --verify HEAD >/dev/null 2>&1
 then
@@ -46,6 +41,14 @@ EOF
 fi
 
 # If there are whitespace errors, print the offending file names and fail.
-git diff-index --check --cached $against --
+git diff-index --check --cached $against -- || EXIT_CODE=$?
 
-python3 -m ansiblelint -v --force-color
+if which python3 &>/dev/null; then
+	python3 -m pip freeze |grep -q '^ansible-lint==' || \
+		python3 -m pip install -U --user ansible-lint
+	python3 -m ansiblelint -v --force-color || EXIT_CODE=$?
+else
+	>&2 echo "Ansible lint not run. Python3 interpreter not found."
+fi
+
+exit $EXIT_CODE
